### PR TITLE
The 2020-03 changes

### LINKED ISSUE #12: Add information/animation if stream is currently not up
As of right now, if stream is not happening, all you'll get is a white box. A way of detecting if JSMpeg is decoding stuff or not, and then add an animation such as Loading, or information to hang on or report an issue, could be done for this.

### LINKED ISSUE #28: Some sort of indicator who the host is
A indicator to show who the host of the room is would be nice

### LINKED ISSUE #57: Smaller player sizes does not take up full size
It'd be better if smaller player sizes, such as 640x480 took up the full height and/or width based on the browser size of the player area. See below for an example of what the player currently looks like now at 640x480 👇 

image

### LINKED ISSUE #73: Dark favicon
By default, the favicon is black which means that it's pretty much invisible if you have dark mode enabled on Google Chrome and other browsers. One solution would be to either change the favicon's color to white or add a white shape around the icon. Google for example is doing that.

image

### LINKED ISSUE #91: WebSocket connection not reconnecting on fail
WebSocket connections from `@cryb/web` to `@cryb/api` does not reconnect when API restarts or another error occurs for example. This transaction should be handled in `store/index.js`

### LINKED ISSUE #103: Logo animation is not working with @cryb/borealis
Cryb Logo
This is no longer animated, since when changing to `@cryb/borealis`, the styles didn't get added there.

https://github.com/crybapp/web/blob/efa2dea8fd45bbc3dc9ddde1418de536429fcde1/components/Header/index.vue#L5

### PR DESCRIPTION
**Pull request by jeda**
These are a few changes I was working on for a while until I had to leave development for a while. As messed-up as it is and can be, it is still pretty much unfinished and needs some work.

This has included a few changes on how things are done, plus new things:
- [X] PWA support (ToDo: Enhance it to be better. but works.)
- [X] Autoplay fix (now you won't be left with a black space)
- [X] Better fullscreen™️ (kinda)
- [X] Player size fix (now takes up the whole available space)
- [X] Picture-in-Picture support (just needs a bit of fixing)
- [X] Assets bundled with script now
- [X] Compressed video for static (ToDo: Actually just change this so it is made by web itself instead of using a video for less page size)
- [X] Owner indicator
- [X] WebSocket connection fixes
- [X] Chat styles fixes and scrolling bar
- [X] Better volume control
- [X] Using less ugly libraries
- [X] Fancy animations and Cryb loading logo
- [X] Removing unneeded files
- [X] Warning for non-HTTPS visitors
- [X] More descriptive errors?
- [x] New icons
- [X] Misc changes/fixes

---

**NOTE**: These have been delayed for a later time.

There's a few things I want to do, like:
- [X] ~~Fix animated avatars. I was changing how this was being done and then didn't.~~ Seems to have never been broken.
- [ ] Fix SSR. It got broken in some point.
- [ ] Include Markdown support in chat
- [ ] Add show keyboard for mobile (the icon shows up but does nothing)
- [ ] Rewrite how volume/buttons are handled (move them to Viewer? Or at least not use store?)
- [ ] Actual better fullscreen. Showing mockups in comments.
- [ ] Auth rewrite (styles messed up and want to make it look better)
- [ ] Modals should be done NOT IN THE WAY THEY ARE BEING DONE RIGHT NOW
- [ ] ~~rewrite store~~
- [ ] Fix properly new room menu (requires changes at `@cryb/api`, for invite creation etc.)
- [ ] lint, less ugly methods
- [ ] even more descriptive things (like why things aren't working)
- [ ] fix some more styling and a few bugs, plus things that should be thrown at `@cryb/borealis`

This PR will be updated as time goes by, including this description to explain more things. Help is appreciated. Fixes/reviews are appreciated while I get back into development and get back on track with this whole unsorted mess again.

Closes #12, closes #28, closes #57, closes #73, closes #91, closes #103, might close more issues soon.

### CODE REVIEW

**Comment by JeDaYoshi** [comment]
Please ignore that. It's the last time. Thank you very much for your understanding.

**Comment by jeda** [comment]
Mentioned issues that will be closed once this PR is merged. Might include more soon as the code is updated.

**Comment by jeda** [comment]
Picking up progress again with this soon. Keep tuned.

**Comment by jeda** [comment]
Since this PR needs to be preferably merged in soon, I'll work in remove the unfinished things, and ensure everything is good to be merged in.

**Comment by jeda** [comment]
Seems good to go now. I'll leave this here to be reviewed. The rest of the missing things will be added later.

**Comment by jeda** [comment]
look at how we make the world burn with a simple button

**Pull request merged**
